optimizer:
  type: AdamW
  lr: 1e-4
  betas: [0.9, 0.999]
  weight_decay: ${if:${debug_mode}, 0.0, 1e-4}
  lr_backbone: 1e-5

lr_config:
  policy: step
  warmup: true
  warmup_iters: 1000
  warmup_ratio: 0.001
  milestones: [20, 40]
  gamma: 0.1